### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by einspunktnull** [yesbotics/dualsense-controller-python#1]
## FIX
- player_leds brightness sets mute led brightness too. can we disable that behavior or do we decouple brightness from player leds?
- lightbar on off
- initial microphone without toggle workaround
- ~~touch finger active state and y value~~
- ~~handle empty mappings~~
- ~~mapping ranges, i.e.when StateValueMapping.DEFAULT stick's middle pos  is -1 instead of 0~~

## RFCT/PERF/OPT

- ~~caching of callbacks possib? -> already cahced and encapsulated~~
- make state threadsafe? or the access/write
- ~~@kappaj: implement your state logic for your change/unchange logic -> cancelled~~
- ~~back mapping on set state values~~ 
- ~~calc  and set deadzone depending on StateValueMapping~~
- ~~option for how remap value range beyond deadzone -> canceled~~

## FEAT
- ~~check contextmanager ability~~
- ~~warning for deadzone/treshold bigger than mapping values~~
- ~~multiproc instead of thread possib? yes but more overhead. thread are good for I/O-bound tasks~~
- once_change
- tests
    - wirite state tests 
    - virtual and real controller switchability
    - internal exceptions
    - ~~invalid deadzone~~
- ~~profile (performance, convenience, custom...) >>> options -> canceled~~
- ~~determine state value if requested (lazy) -> canceled~~
- ~~disconnect for bt possib? check https://github.com/pybluez/pybluez -> canceled~~

- ~~complex state packets:~~
    - ~~touch finger 0 and 1~~
    - ~~orientation~~
    - ~~battery~~
    - ~~r2 and l2 feedback~~
    - ~~all_in_one -> canceled~~
        - ~~complex and non complex -> canceled~~
        - ~~primitive only -> canceled~~
        - ~~complex only -> canceled~~

    - ~~touch fingers (both) -> canceled~~

    - ~~L2 (Btn and analog) -> canceled~~

- impl set properties (rumble, triggerFX, li50ghts, ...)
- impl raw report in/out (hex)

## DOCS
- changelog
- create documentation (add doc comments)
- explain (Getting started)
- rework example
- docs: table for input report like out report

**Comment by SamuelTagliabracci** [comment]
Great work on the DS5 library.

Question about the microphone. Any advice on how to get the DS5 microphone working on Ubuntu 22 or how it actually shows up?

**Comment by einspunktnull** [comment]
Hi @SamuelTagliabracci,

this library does not support microphone use, as this is handled at operating system level. However, if you connect the Mircophone to the Ubuntu computer via **USB-cable**, the microphone should be registered as a regular microphone device in the audio settings (see screenshot).

![Screenshot_20240228_120917](https://github.com/yesbotics/dualsense-controller-python/assets/1256157/17121205-469d-44ac-a53a-d4ccf6f1a4bc)
This is how it looks in Manjaro with KDE Plasma, in Ubuntu it should also appear in the corresponding audio device list
