### ISSUE TITLE
Orientation get Yaw is None.. ?

### ISSUE THREAD

**Issue by foxshared** [yesbotics/dualsense-controller-python#7]
result from get Orientation

on_orientation_change: Orientation(pitch=82.69, roll=351.19, yaw=None)
on_orientation_change: Orientation(pitch=81.69, roll=352.92, yaw=None)
on_orientation_change: Orientation(pitch=80.95, roll=357.76, yaw=None)

do i need to do something?

**Comment by einspunktnull** [comment]
unfortunately, this value is not supplied by the controller. i will remove the value in future.
